server:
  port: 8888

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:db/test.db #相对位置

  jpa:
    hibernate:
      ddl-auto: update # 自动更新
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #更改默认命名策略
    show-sql: true  # 控制台打印SQl语句
    database-platform: com.sea.review.config.SQLiteDialect




